export enum RoutePageEnum {
  empty = '',
  home = '/home',
  login = '/login',
  registration = '/registration',
  dashboard = '/dashboard',
  dashboardVetSettings = '/dashboard/vet/settings',
  dashboardVetAppointment = '/dashboard/vet/appointment',
  dashboardVetClient = '/dashboard/vet/client',
  dashboardVetEmployment = '/dashboard/vet/employment',
  dashboardVetInvoice = '/dashboard/vet/invoice',
  dashboardVetMedicalRecord = '/dashboard/vet/medical-record',
  dashboardVetMedication = '/dashboard/vet/medication',
  dashboardVetOpeningHour = '/dashboard/vet/opening-hour',
  dashboardVetPet = '/dashboard/vet/pet',
  dashboardVetServiceClinic = '/dashboard/vet/service-clinic',
  dashboardVetClinic = '/dashboard/vet/clinic',
  dashboardChooseRole = '/dashboard/choose-role',
  dashboardAccountSettings = '/dashboard/account-settings',
  dashboardProfile = '/dashboard/profile',
}

export enum RouteSectionEnum {
  empty = '',
  home = 'home',
  aboutUs = 'about-us',
  price = 'price',
  contact = 'contact',
  login = 'login',
  registration = 'registration',
  dashboard = 'dashboard',
  dashboardVet = 'dashboard-vet',
  dashboardVetSettings = 'vet-account-settings',
  dashboardVetAppointment = 'dashboard-vet-appointment',
  dashboardVetClient = 'dashboard-vet-client',
  dashboardVetEmployment = 'dashboard-vet-employment',
  dashboardVetInvoice = 'dashboard-vet-invoice',
  dashboardVetMedicalRecord = 'dashboard-vet-medical-record',
  dashboardVetMedication = 'dashboard-vet-medication-record',
  dashboardVetOpeningHour = 'dashboard-vet-opening-hour',
  dashboardVetPet = 'dashboard-vet-pet',
  dashboardVetServiceClinic = 'dashboard-vet-service-clinic',
  dashboardVetClinic = 'dashboard-vet-clinic',
  dashboardChooseRole = 'dashboard-choose-role',
  dashboardAccountSettings = 'dashboard-account-settings',
  dashboardProfile = 'dashboard-profile',
}
