export enum RoutePageEnum {
  empty = '',
  home = '/home',
  login = '/login',
  registration = '/registration',
  dashboard = '/dashboard',
  dashboardAccountSettings = '/dashboard/account-settings',
  dashboardProfile = '/dashboard/profile',
  dashboardVetSettings = '/dashboard/vet/settings',
  dashboardVetClinic = '/dashboard/vet/clinic',
  dashboardVetClinicOpeningHours = '/dashboard/vet/clinic-opening-hours',
  dashboardVetEmployment = '/dashboard/vet/employment',
  dashboardVetMedicalRecord = '/dashboard/vet/medical-record',
  dashboardVetMedication = '/dashboard/vet/medication',
  dashboardVetService = '/dashboard/vet/service',
  dashboardVetAppointment = '/dashboard/vet/appointment',
  dashboardVetInvoice = '/dashboard/vet/invoice',
  dashboardVetClients = '/dashboard/vet/clients',
  dashboardVetPatients = '/dashboard/vet/patients',
  dashboardChooseRole = '/dashboard/choose-role',
}

export enum RouteSectionEnum {
  empty = '',
  home = 'home',
  aboutUs = 'about-us',
  price = 'price',
  contact = 'contact',
  login = 'login',
  registration = 'registration',
  dashboard = 'dashboard',
  dashboardAccountSettings = 'dashboard-account-settings',
  dashboardProfile = 'dashboard-profile',
  dashboardVet = 'dashboard-vet',
  dashboardVetSettings = 'vet-account-settings',
  dashboardVetClinic = 'dashboard-vet-clinic',
  dashboardVetMedicalRecord = 'dashboard-vet-medical-record',
  dashboardVetMedication = 'dashboard-vet-medication-record',
  dashboardVetService = 'dashboard-vet-service',
  dashboardVetEmployment = 'dashboard-vet-employment',
  dashboardVetClinicOpeningHours = 'dashboard-vet-clinic-opening-hours',
  dashboardVetAppointment = 'dashboard-vet-appointment',
  dashboardVetInvoice = 'dashboard-vet-invoice',
  dashboardVetClients = 'dashboard-vet-clients',
  dashboardVetPatients = 'dashboard-vet-patients',
  dashboardChooseRole = 'dashboard-choose-role',
}
