export enum RoutePageEnum {
  empty = '',
  home = '/home',
  login = '/login',
  registration = '/registration',
  dashboard = '/dashboard',
  dashboardAccountSettings = '/dashboard/account-settings',
  dashboardProfile = '/dashboard/profile',
  dashboardVet = '/dashboard/vet',
  dashboardVetSettings = '/dashboard/vet/settings',
  dashboardVetClinic = '/dashboard/vet/clinic',
  dashboardVetMedicalRecord = '/dashboard/vet/medical-record',
  dashboardVetMedication = '/dashboard/vet/medication',
  dashboardVetServices = '/dashboard/vet/services',
  dashboardVetAppointment = '/dashboard/vet/appointment',
  dashboardVetInvoice = '/dashboard/vet/invoice',
  dashboardVetPatients = '/dashboard/vet/patients',
  dashboardClient = '/dashboard/client',
  dashboardChooseRole = '/dashboard/choose-role'
}

export enum RouteSectionEnum {
  empty = '',
  home = 'home',
  aboutUs = 'about-us',
  price = 'price',
  contact = 'contact',
  login = 'login',
  registration = 'registration',
  dashboard = 'dashboard',
  dashboardAccountSettings = 'dashboard-account-settings',
  dashboardProfile = 'dashboard-profile',
  dashboardVet = 'dashboard-vet',
  dashboardVetSettings = 'vet-account-settings',
  dashboardVetClinic = 'dashboard-vet-clinic',
  dashboardVetMedicalRecord = 'dashboard-vet-medical-record',
  dashboardVetMedication = 'dashboard-vet-medication-record',
  dashboardVetServices = 'dashboard-vet-services',
  dashboardVetAppointment = 'dashboard-vet-appointment',
  dashboardVetInvoice = 'dashboard-vet-invoice',
  dashboardVetPatients = 'dashboard-vet-patients',
  dashboardClient = 'dashboard-client',
  dashboardChooseRole = 'dashboard-choose-role'
}
