export * from './lib/root/dashboard/dashboard-page.component';
export * from './lib/root/home/home-page.component';
export * from './lib/root/login/login-page.component';
export * from './lib/root/registration/registration-page.component';
export * from './lib/root/root-page.component';
export * from './lib/root/dashboard/choose-role/choose-role-page.component';
export * from './lib/root/dashboard/dashboard-main/dashboard-main-page.component';
export * from './lib/root/dashboard/vet/vet-page.component';
export * from './lib/root/dashboard/client/client-page.component';
