export enum EndpointEnum {
  chooseRole = 'choose-role',
  login = 'login',
  logout = 'logout',
  registration = 'registration',
  getAccount = 'get-account',
  hasRole = 'has-role',
  isClient = 'is-client',
  isVet = 'is-vet',
  validToken = 'valid-token',
  clinicCreate = 'clinic-create',
  clinicRead = 'clinic-read',
  clinicUpdate = 'clinic-update',
  clinicDelete = 'clinic-delete',
  serviceCreate = 'service-create',
  serviceRead = 'service-read',
  serviceUpdate = 'service-update',
  serviceDelete = 'service-delete',
  clinicOpeningHoursRead = 'clinic-opening-hours-read',
  clinicOpeningHoursUpdate = 'clinic-opening-hours-update',
}
