export enum EndpointEnum {
  auth = 'auth',
  chooseRole = 'choose-role',
  hasRole = 'has-role',
  isClient = 'is-client',
  isVet = 'is-vet',
  login = 'login',
  logout = 'logout',
  registration = 'registration',
  getAccount = 'get-account',
  clinicCreate = 'clinic/create',
  clinicRead = 'clinic/read',
  clinicUpdate = 'clinic/update',
  clinicDelete = 'clinic/delete',
}
