export enum EndpointEnum {
  chooseRole = 'choose-role',
  login = 'login',
  logout = 'logout',
  registration = 'registration',
  getAccount = 'get-account',
  hasRole = 'has-role',
  validToken = 'valid-token',
  clinicCreate = 'clinic-create',
  clinicRead = 'clinic-read',
  clinicUpdate = 'clinic-update',
  clinicDelete = 'clinic-delete',
  vetServiceCreate = 'vet-service-create',
  vetServiceRead = 'vet-service-read',
  vetServiceUpdate = 'vet-service-update',
  vetServiceDelete = 'vet-service-delete',
  clinicOpeningHoursRead = 'clinic-opening-hours-read',
  clinicOpeningHoursUpdate = 'clinic-opening-hours-update',
  employmentCreate = 'employment-create',
  employmentRead = 'employment-read',
  employmentUpdate = 'employment-update',
  employmentDelete = 'employment-delete',
  medicationCreate = 'medication-create',
  medicationRead = 'medication-read',
  medicationUpdate = 'medication-update',
  medicationDelete = 'medication-delete',
}
